name: Slack Reply to GitHub Discussion

on:
  repository_dispatch:
    types: [slack-reply]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post Reply to GitHub Discussion
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -H "Content-Type: application/json" \
               -d '{
                 "body": "${{ github.event.client_payload.message }}"
               }' \
               "https://api.github.com/repos/hyerin082197/tech-support/issues/comments"
