name: Slack Reply to GitHub Discussion

on:
  issue_comment:
    types: [created]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post Reply to GitHub Discussion
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/hyerin082197/tech-support/issues/comments \
               -d '{
                 "body": "${{ github.event.comment.body }}"
               }'
